from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol

from model_to_harness_shared import DuplicateEvidence, WorkflowOutcome

from .models import (
    ApprovalDecision,
    ApprovalResponse,
    DurableEvent,
    RefundLedgerEntry,
    WorkflowState,
)


class Repository(Protocol):
    async def initialize(self) -> None: ...

    async def close(self) -> None: ...

    async def check_ready(self) -> None: ...

    async def create_run(self, state: WorkflowState) -> None: ...

    async def save_state(self, state: WorkflowState) -> None: ...

    async def get_state(self, run_id: str) -> WorkflowState | None: ...

    async def get_state_by_case(self, case_id: str) -> WorkflowState | None: ...

    async def save_memory(self, case_id: str, memory: dict[str, object]) -> None: ...

    async def get_memory(self, case_id: str) -> dict[str, object]: ...

    async def append_event(self, event: DurableEvent) -> DurableEvent: ...

    async def list_events(self, run_id: str, after: int = 0) -> list[DurableEvent]: ...

    async def save_approval(
        self, run_id: str, checkpoint_id: str, response: ApprovalResponse
    ) -> None: ...

    async def get_approval(self, run_id: str) -> ApprovalResponse | None: ...

    async def save_outcome(self, outcome: WorkflowOutcome) -> None: ...

    async def get_outcome(self, run_id: str) -> WorkflowOutcome | None: ...

    async def set_checkpoint(self, run_id: str, checkpoint_id: str) -> None: ...

    async def get_refund(self, idempotency_key: str) -> RefundLedgerEntry | None: ...

    async def store_refund(self, entry: RefundLedgerEntry) -> tuple[RefundLedgerEntry, bool]: ...

    async def count_refunds(self, idempotency_key: str) -> int: ...


@dataclass(frozen=True)
class ModelResult:
    text: str
    latency_ms: int
    model: str


class ModelClient(Protocol):
    async def normalize_complaint(self, complaint: str) -> ModelResult: ...

    async def draft_notification(self, facts: dict[str, object]) -> ModelResult: ...

    async def explain_run(self, question: str, facts: dict[str, object]) -> ModelResult: ...

    async def close(self) -> None: ...


class Actions(Protocol):
    last_evidence: DuplicateEvidence | None

    @property
    def maximum_read_attempts(self) -> int: ...

    @property
    def verification_count_override(self) -> int | None: ...

    def load_account(self) -> dict[str, Any]: ...

    def detect_duplicate(self) -> dict[str, Any]: ...

    def validate_billing(self, evidence_data: dict[str, Any]) -> dict[str, Any]: ...

    def validate_policy(
        self, evidence_data: dict[str, Any], account_summary: dict[str, Any]
    ) -> dict[str, Any]: ...

    def request_approval(self, evidence_data: dict[str, Any], case_id: str) -> dict[str, Any]: ...

    def resolve_approval(
        self, decision: ApprovalDecision, reviewer_id: str, reason: str | None
    ) -> dict[str, Any]: ...

    def refund_request(self, idempotency_key: str) -> dict[str, Any]: ...

    def submit_refund(self, idempotency_key: str) -> dict[str, Any]: ...

    def find_refund(self, idempotency_key: str) -> dict[str, Any] | None: ...


class WorkflowRunner(Protocol):
    async def start(self, state: WorkflowState) -> None: ...

    async def resume(
        self, state: WorkflowState, checkpoint_id: str, approval: ApprovalResponse
    ) -> None: ...
