from typing import Any

WORKFLOW_GRAPH: dict[str, Any] = {
    "nodes": [
        "normalize_complaint",
        "load_account",
        "detect_duplicate",
        "prepare_validation",
        "billing_validation",
        "policy_validation",
        "join_validations",
        "approval_checkpoint",
        "submit_refund",
        "verify_refund",
        "notify_customer",
        "close_case",
        "close_no_duplicate",
        "close_denied",
        "route_failure",
        "manual_review",
    ],
    "edges": [
        ["normalize_complaint", "load_account"],
        ["load_account", "detect_duplicate", "loaded"],
        ["load_account", "route_failure", "read_failed"],
        ["detect_duplicate", "prepare_validation", "duplicate"],
        ["detect_duplicate", "close_no_duplicate", "no_duplicate"],
        ["prepare_validation", "billing_validation"],
        ["prepare_validation", "policy_validation"],
        ["billing_validation", "join_validations"],
        ["policy_validation", "join_validations"],
        ["join_validations", "approval_checkpoint", "valid"],
        ["join_validations", "route_failure", "invalid"],
        ["approval_checkpoint", "submit_refund", "approved"],
        ["approval_checkpoint", "close_denied", "denied"],
        ["submit_refund", "verify_refund"],
        ["verify_refund", "notify_customer", "exactly_one"],
        ["verify_refund", "manual_review", "mismatch"],
        ["notify_customer", "close_case"],
    ],
    "parallel_groups": [["billing_validation", "policy_validation"]],
}
